title: "The Drunk Fist"
logo: https://scontent-lhr3-1.xx.fbcdn.net/v/t1.0-9/12924327_1055493701181167_8864637288132645323_n.jpg?oh=e23da680e79c14003b0e75cb20a7a47e&oe=5804AE4F
email: john@thedrunkfist.com
description: >
  The drunk fist is my progress from a drunken developer into a full time carer who has stopped smoking, stopped
  drinking and started to take up boxing, muay thai, bjj, mma and generally just trying to be better.
url: "http://thedrunkfist.com"
twitter_username: drunkyfist
github_username:  solrevdev
baseurl: ''
permalink: pretty
paginate: 5

markdown: kramdown
highlighter: rouge

gems:
  - jekyll-sitemap
  - jekyll-paginate
