# Plugins
gems:
  - github-pages
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed


# Dependencies
highlighter: rouge
markdown: kramdown

# Permalinks
# excerpt_separator: ''
permalink:         pretty

# Setup
title:            'The Drunk Fist'
logo:             'https://scontent-lht6-1.xx.fbcdn.net/v/t1.0-1/p200x200/13912758_1140624079334795_4992427127729796926_n.jpg?oh=21f7632d5db4e00ed5eb05cb0607621a&oe=5A19FCA4'
description: >
  The drunk fist is my progress from a drunken developer into a full time carer who has stopped smoking, stopped
  drinking and started to take up boxing, muay thai, bjj, mma and generally just trying to be better.
url:              'https://thedrunkfist.com'
baseurl:          ''

# Contacts
author:
  name:           'John Smith'
  url:            'https://thedrunkfist.com/about/'
  email:          "john@thedrunkfist.com"
  github:         'https://github.com/solrevdev/thedrunkfist'
  facebook:       'https://www.facebook.com/thedrunkfist'
  instagram:      'https://www.instagram.com/thedrunkfist'
  twitter:        'https://twitter.com/drunkyfist'

email:            'john@thedrunkfist.com'
twitter_username: 'drunkyfist'
github_username:  'solrevdev'

# Outputting
paginate: 5

# Custom vars
version:          '2.1.0'

github:
  repo:           'https://github.com/solrevdev/thedrunkfist'

exclude: ['Rakefile', 'vendor']

# Social Sharing
facebook_app_id: '1592824447677017'
